### ISSUE TITLE
4.x as master

### ISSUE THREAD

**Issue by slavkoja** [KiCad/kicad-i18n#116]
Please, make the 4.0 branch as master. IMO, it is confusing, when the default (master) branch doesn't show current status and one need to switch the branch after clone. Or i miss something?

**Comment by ciampix** [comment]
IMHO your suggestion is a bad idea. Master is the dev branch and the i18n repository is organized likewise the git repository of source code. Why the i18n repository should differ from the source code repository it correspond?

**Comment by slavkoja** [comment]
OK, i was only surprised, when i take look on sk translation status and on the default page it is 2 years old, but there was new added. Then i find it under the 4.0 branch. Then my main idea was, that the default branch have provide current status, but i never take look into the kicad's source repo organization. It makes sense now. I am sorry for noise ;-)
