### ISSUE TITLE
Proposal: What about a kicad-i18n mailing list?

### ISSUE THREAD

**Issue by timofonic** [KiCad/kicad-i18n#20]
Hello.

I would like that there's a kicad-i18n mailing list. Maybe we can use the developers' ml, but some stuff might be too specific.

I'm trying to translate a bit of the file, not sure if there's ongoing work. I hope there's no conflict on it and others can fix my mistakes. I'm far from perfect and this is my first try at translating software, but I want to learn and collaborate actively in the translation process. 
I don't do it exactly for myself, but to promote KiCad in the Spanish countries and FOSS in electronics. Electronics software is usually very expensive and my ideals are pro-FOSS too. I'm not a programmer, but I would like to contribute to make the situation better.

Other than that, it would be nice to have specific mailing lists for each language. This way, coordination would be easier too. Maybe I'm wrong, just provide me the feedback if it's a good or bad idea.

Kind regards.

**Comment by ciampix** [comment]
I am closing this. I think there are not enough resources to open another ml. And IMHO a "doc" ml should come first anyway...
