### ISSUE TITLE
String should be split

### ISSUE THREAD

**Issue by ejs-ejs** [KiCad/kicad-i18n#26]
Dear maintainers,

i've found confusing merge of strings to be translated: 
a string ID #2132 "Circular" defines both pad shape and the type of array. Need to mention "hole" and "array" are of different genders in some languages and needs to be matched in the translation.

IMHO, these strings from pcbnew/dialogs/dialog_pad_properties_base.cpp (line 68) and pcbnew/dialogs/dialog_create_array_base.cpp (line 281) should be separated.

**Comment by jp-charras** [comment]
Le 21/11/2015 23:59, ejs-ejs a écrit :
> Dear maintainers,
> 
> i've found confusing merge of strings to be translated:
> a string ID #2132 "Circular" defines both pad shape and the type of
> array. Need to mention "hole" and "array" are of different genders in
> some languages and needs to be matched in the translation.
> 
> IMHO, these strings from pcbnew/dialogs/dialog_pad_properties_base.cpp
> (line 68) and pcbnew/dialogs/dialog_create_array_base.cpp (line 281)
> should be separated.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-i18n/issues/26>.
> 

dialog_create_array_base.cpp modified in rev 6327.

-- 
Jean-Pierre CHARRAS

**Comment by ciampix** [comment]
Thanks report this.
