### ISSUE TITLE
fr translation update

### ISSUE THREAD

**Issue by Thaeron** [KiCad/kicad-i18n#402]
I fixed 2 errors in french translation.

diff --git a/fr/kicad.po b/fr/kicad.po
index f1118ca..fb13634 100644
--- a/fr/kicad.po
+++ b/fr/kicad.po
@@ -3667,7 +3667,7 @@ msgstr "Réinitialiser à Défaut"
 
 #: common/widgets/widget_hotkey_list.cpp:435
 msgid "Undo All Changes"
-msgstr "Unnuler tous les Changements"
+msgstr "Annuler tous les Changements"
 
 #: common/widgets/widget_hotkey_list.cpp:436
 msgid "Restore All to Default"
@@ -11856,7 +11856,7 @@ msgstr "Ouvrir schématique"
 
 #: eeschema/tool_sch.cpp:71
 msgid "Save (all sheets)"
-msgstr "Quitter (toutes les feuilles)"
+msgstr "Sauver (toutes les feuilles)"
 
 #: eeschema/tool_sch.cpp:76
 msgid "Edit Page settings"

[kicad.po.gz](https://github.com/KiCad/kicad-i18n/files/3147802/kicad.po.gz)
[fr.diff.gz](https://github.com/KiCad/kicad-i18n/files/3147801/fr.diff.gz)

**Comment by ciampix** [comment]
Thanks!
